GET http://localhost:4000/carList

###
POST http://localhost:4000/carList
Content-Type: application/json

{
    "name" : "jazz",
    "fuelType":  "Petrol",
    "fuelTankSize" : "100L",
    "completedJourney" : 4,
    "distanceCovered" : 100
}